---
- name: Install basic packages
  package:
    name: '{{ packages_to_install }}'
    state: present
  become: true

- name: Ensure curl is installed
  ansible.builtin.package:
    name: curl
    state: present

- name: Check if k3s binary exists
  stat:
    path: /usr/local/bin/k3s
  register: k3s_binary


- name: Install k3s master nodes using the provided script
  ansible.builtin.shell: >-
    curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL={{ k3s_channel }} INSTALL_K3S_EXEC="{{ k3s_exec }}" sh -s -
  become: true
  when: inventory_hostname in groups['master'] and not k3s_binary.stat.exists

# - name: Get K3S_TOKEN from all master nodes
#   delegate_to: '{{ item }}'
#   ansible.builtin.shell: cat /var/lib/rancher/k3s/server/node-token
#   register: master_token_results
#   loop: "{{ groups['master'] }}"
#   become: true
#   run_once: true
#   when: inventory_hostname in groups['worker']

- name: Get K3S_TOKEN from master node
  delegate_to: "{{ groups[master_group_name][0] }}"
  ansible.builtin.shell: cat /var/lib/rancher/k3s/server/node-token
  register: master_token_result
  run_once: true
  become: true

- name: "Install k3s on worker nodes {{hostvars[groups['master'][0]]['ansible_host']}}"
  ansible.builtin.shell: >-
    curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL={{ k3s_channel }}  K3S_URL=https://{{
    hostvars[groups['master'][0]]['ansible_host'] }}:6443 K3S_TOKEN={{ master_token_results.results[0].stdout }} sh -s -
  # ansible.builtin.shell: >-
  #   echo hello
  become: true

# when: inventory_hostname in groups['worker'] and not k3s_binary.stat.exists
# - name: Reboot machine after installing k3s
#   ansible.builtin.reboot:
#   become: true

##

# - name: Clean up k3s master nodes installation files
#   ansible.builtin.shell: >-
#     /usr/local/bin/k3s-uninstall.sh
#   become: true
#   when: inventory_hostname in groups['master'] and k3s_binary.stat.exists

# - name: Clean up k3s worker node installation files
#   ansible.builtin.shell: >-
#     /usr/local/bin/k3s-agent-uninstall.sh
#   become: true
#   when: inventory_hostname in groups['worker'] and k3s_binary.stat.exists

