apiVersion: v1
kind: PersistentVolume
metadata:
  name: memos-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: "/home/le/.memos"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: memos-pvc
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memos-deployment
  labels:
    app: memos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memos
  template:
    metadata:
      labels:
        app: memos
    spec:
      containers:
      - name: memos
        image: ghcr.io/usememos/memos:latest
        ports:
        - containerPort: 5230
        volumeMounts:
        - name: memos-storage
          mountPath: /var/opt/memos
      volumes:
      - name: memos-storage
        persistentVolumeClaim:
          claimName: memos-pvc
---
