---
- name: Deploy Jenkins container
  hosts: all
  tasks:
    - name: Ensure Jenkins Docker image is installed
      ansible.builtin.docker_image:
        name: jenkins/jenkins:lts-jdk11
        source: pull

    - name: Create Jenkins data directory
      ansible.builtin.file:
        path: '{{ ansible_env.HOME }}/jenkins_home'
        state: directory
        owner: '{{ ansible_user_id }}'
        group: '{{ ansible_user_id }}'
        mode: '0755'

    - name: Ensure jenkins_network Docker network exists
      ansible.builtin.docker_network:
        name: jenkins_network
        state: present

    - name: Deploy Jenkins Docker container
      ansible.builtin.docker_container:
        name: jenkins
        image: jenkins/jenkins:lts-jdk11
        state: started
        restart_policy: on-failure
        ports:
          - 8085:8080
          - 50000:50000
        volumes:
          - ~/jenkins_home:/var/jenkins_home
        networks:
    - name: jenkins_network

    - name: Ensure socat Docker image is installed
      ansible.builtin.docker_image:
        name: alpine/socat
        source: pull

    - name: Deploy socat Docker container
      ansible.builtin.docker_container:
        name: socat
        image: alpine/socat
        state: started
        restart_policy: always
        command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
        ports:
          - 2375:2375
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        networks:
          - name: jenkins_network
