---
- name: Set Python interpreter
  hosts: all
  tasks:
    - name: Set Python asdf
      set_fact:
        ansible_python_interpreter: /home/{{ ansible_user_id }}/.asdf/shims/python3
        ansible_pip_executable: /home/{{ ansible_user_id }}/.asdf/shims/pip3
