---
- name: Update apt cache
  apt:
    update_cache: yes
    upgrade: 'yes'

- name: Add user
  user:
    name: '{{ username }}'
    shell: /bin/bash
    create_home: yes

- name: Set the timezone
  timezone:
    name: '{{ timezone }}'

- name: Install basic packages
  package:
    name: '{{ packages_to_install }}'
    state: present
