---
- name: Apply common configurations to all hosts
  hosts: all
  roles:
    - common
  become: true

- name: Setup Master node
  hosts: master
  roles:
    - dev_tools
    - k3s

- name: Setup Worker node
  hosts: worker
  roles:
    - database
