version: '3.9'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    restart: on-failure
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./var/jenkins_home:/var/jenkins_home
    # networks:
    #   - jenkins
