---
- name: Apply common configurations to all hosts
  hosts: all
  roles:
    - common

- name: Setup Master node
  hosts: master
  roles:
    - dev_tools
# - name: Setup Worker node
#   hosts: worker
#   roles:
#     - database
