---
- name: Deploy Filebrowser using Docker
  hosts: all
  tasks:
    - name: Gather user and group ID
      command: id -u "{{ ansible_user_id }}"
      register: user_id
      changed_when: false
    - command: id -g "{{ ansible_user_id }}"
      register: group_id
      changed_when: false

    - name: Create Filebrowser directory
      ansible.builtin.file:
        path: '{{ ansible_env.HOME }}/filebrowser'
        state: directory
        owner: '{{ ansible_user_id }}'
        group: '{{ ansible_user_id }}'
        mode: '0777'

    - name: Create database.db file
      ansible.builtin.file:
        path: '{{ ansible_env.HOME }}/filebrowser/database.db'
        # owner: "{{ ansible_user_id}}"
        # group: "{{ ansible_user_id }}"
        state: touch
        mode: '0777'

    - name: Run Filebrowser Docker container
      community.docker.docker_container:
        name: filebrowser
        image: filebrowser/filebrowser
        state: started
        restart_policy: always
        published_ports:
          - '8081:80'
        volumes:
          - '{{ ansible_env.HOME }}/:/srv/home'
          # - '/mnt/external-ssd/:/srv/external'
          - '{{ ansible_env.HOME }}/filebrowser/database.db:/database.db'
        user: '{{ ansible_user_uid }}:{{ ansible_user_gid }}'
