---
- name: Deploy MinIO using Docker
  hosts: all
  become: true
  tasks:
    - name: Create MinIO data directory
      ansible.builtin.file:
        path: '{{ ansible_env.HOME }}/minio/data'
        state: directory
        owner: '{{ ansible_user_id }}'
        group: '{{ ansible_user_id }}'
        mode: '0755'

    - name: Ensure Docker is installed
      ansible.builtin.package:
        name: docker
        state: present

    - name: Ensure MinIO Docker container is running
      community.docker.docker_container:
        name: minio
        image: quay.io/minio/minio
        state: started
        pull: true
        env:
          MINIO_ROOT_USER: ROOTNAME
          MINIO_ROOT_PASSWORD: CHANGEME123
        volumes:
          - '{{ ansible_env.HOME }}/minio/data:/data'
        published_ports:
          - '9009:9000'
          - '9090:9090'
        command: server /data --console-address ":9090"
