---
- hosts: all
  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - lsb-release
          - gnupg
        state: latest
        update_cache: true
      become: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: true

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
      become: true

    - name: Update apt and install docker-ce
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: true
      become: true

    - name: Enable and start docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: true

    - name: test docker
      command: docker info
      become: true

    - name: Create docker group
      group:
        name: docker
        state: present
      become: true

    - name: Add user to docker group
      user:
        name: '{{ ansible_user_id }}'
        groups: docker
        append: yes
      become: true

    - name: Install Docker Compose using ASDF Python
      shell: |
        source /home/{{ ansible_user_id }}/.asdf/asdf.sh
        pip install docker-compose
      args:
        executable: /usr/bin/zsh
      become_user: '{{ ansible_user_id }}'

  handlers:
    - name: restart docker
      service:
        name: docker
        state: restarted
      become: true
